#ifndef PL_ADDRESSES_H
#define PL_ADDRESSES_H

#define ADDRESS_ID 0x00
#define ADDRESS_DISPFREQ 0x01
#define ADDRESS_DISPMODE 0x02
#define ADDRESS_RXMODE 0x03
#define ADDRESS_PHACC1 0x04
#define ADDRESS_FFTACC 0x05



#endif // PL_ADDRESSES_H
